### PR TITLE
Ensures filters aren't case sensitive removes duplicate files

### LINKED ISSUE #537: VM name filter is case sensitive
Description of problem:

VM name filter is case sensitive

Version-Release number of selected component (if applicable):

5.9.4.2 (Red Hat CloudForms 4.6) 

How reproducible: 100%

Steps to Reproduce:

1. Login to the CloudForms operational portal

2. Create infrastructure mapping.

- Navigate to Compute -> Migration -> Create infrastructure mapping -> Save

3. Create migrate plan

- Navigate to Compute -> Migration -> Create infrastructure mapping -> specify general information -> Go to VMs -> Filter by VM 

Actual results: VM name filter is case sensitive

Expected results: VM name "filter by VM" should not be case sensitive.

### PR DESCRIPTION
**Pull request by AllenBW**
fixes #537
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612047

### loooooook all better now
screen shot 2018-08-03 at 1 26 19 pm

cc @bthurber

### CODE REVIEW

File: app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/searchFilter.js [hunk 1]
```diff
@@ -1,23 +0,0 @@
...
-    rows.forEach(row => {
-      const match = Object.values(row).some(value => `${value || ''}`.indexOf(searchFilterValue) > -1);
-      if (match) {
-        filteredRows.push(row);
-      }
-    });
-    return filteredRows;
-  }
-  return rows;
-}
```
Comment (michaelkro) [inline app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/searchFilter.js]: Ahhh, feels good 🛀

Comment (AllenBW) [reply app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/searchFilter.js]: ☺️
